#!/bin/bash

#----------------------------------------------------

echo -e "\033[33mInstalar\033[1m\033[4m\033[32mPlexServer\033[0m\033[0m en ArchLinux"

# Instalar Plex
echo -e "\033[31mInstalando Plex Server...\033[0m"
yay -S plex-media-server


# Iniciar el servicio de Plex
#echo "\033[31mIniciando Plex Media Server y habilitando dn el arranque...\033[0m"
#sudo systemctl start plexmediaserver
#sudo systemctl enable plexmediaserver

# Comprobar el estado del servicio
echo -e "\033[31mComprobando el estado de Plex Media Server...\03q3[0m"
sudo systemctl status plexmediaserver


echo -e "


\033[1m\033[4m\033[33mLa instalacion de PlexServer ha finalizado PlexServer\033[0m

La URL del servicio es:

        \033[1m\033[33mhttp://localhost:32400/web\033[0m

"

