#!/bin/bash

#----------------------------------------------------

echo -e "\033[33mInstalar\033[1m\033[4m\033[32mPlexServer\033[0m\033[0m en ArchLinux"

# Instalar Plex
echo -e "\033[31mInstalando Plex Server...\033[0m"
yay -S plex-media-server


#----------------------------------------------------

clear

echo -e "

\033[1m\033[4m\033[33mInstalacion finalizada correctamente\033[0m

\033[1m\033[32mResumen de la instalacion:\033[0m

- Se ha actualizado SO
- Se han instalado los siguientes paquetes:\033[1m\033[33m

            git             net-tools           inkscape            texmaker
            wget            neovim              hexchat             powerline-fonts
            kate            gparted             qbittorrent         gnome-boxes
            feh             curl                putty               vscode
            p7zip           fastfetch           thunderbird         plex-media-server
            locate          kitty               keepass             zsh
            lsd             dolphin             keepassxc           MediaWriter
            bat             gimp                texlive\033[0m

- Se ha verificado actualizaciones
- Se ha cambiado la Shell a ZSH para el Usuario y Root
- Se ha añadido Powerlevel10k y añadido los plugins para ZSH en Usuario y Root\033[1m\033[33m

            Syntax Highlighting
            Autosuggestions
            zsh-z
            Fast Syntax Highlighting
            Autocomplete
            fzf\033[0m

- Se ha descargado y configurando las fuentes Meslo
- Se han copiando configuraciones personalizadas zshrc y p10k
- Se levanta el servicio PlexServer

        URL: \033[1m\033[33mhttp://localhost:32400/web\033[0m

"
